#!/usr/bin/env zsh

###############################
# EXPORT ENVIRONMENT VARIABLE #
###############################

# XDG
export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$XDG_CONFIG_HOME/cache
# default on linux
# export XDG_DATA_HOME=$XDG_CONFIG_HOME/local/share
# default on mac
# export XDG_DATA_HOME=$HOME/Library/Application Support

# editor
export EDITOR="code --wait"
export VISUAL="code --wait"

# zsh
export ZDOTDIR=$XDG_CONFIG_HOME/zsh

# Brew
export HOMEBREW_EVAL_ALL=true

# GNU Commands
# true  => zprofile will load GNU commands with his names
# false => GNU commands with prefix g
export USE_GNU_COMMANDS=true

# locale
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# EXA
export EXA_COLORS="in=0;38:lc=0;38:ur=0;33:uw=0;33:ux=0;33:ue=0;33:gr=0;37:gw=0;37:gx=0;37:tr=0;31:tw=0;31:tx=0;31:da=0;36:uu=0;33:gu=0;37"

# zsh help
export HELPDIR=/usr/share/zsh/5.8.1/help

# tmux
export TMUX_HOME=$XDG_CONFIG_HOME/tmux

# Color
export CLICOLOR=1

# rg
export RIPGREP_CONFIG_PATH=$XDG_CONFIG_HOME/rg/ripgreprc

# FZF
export FZF_HISTFILE=$ZDOTDIR/.fzf_history

export FZF_DEFAULT_COMMAND='rg --files'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

export FZF_DEFAULT_OPTS="\
	--history=$FZF_HISTFILE \
	--ansi \
	--height 60% \
	--border sharp \
	--layout reverse \
	--prompt '∷ ' \
	--pointer ▶ \
	--marker ⇒ \
	--bind change:first"

# --color=dark,hl:33,hl+:37,fg+:235,bg+:136,fg+:254 --color info:254,prompt:37,spinner:108,pointer:235,marker:235
export FZF_ALT_C_OPTS="--preview 'tree -C {}'"
export FZF_COMPLETION_DIR_COMMANDS="cd pushd rmdir tree"

