#! /usr/bin/env bash
mime=$(file -Lbs --mime-type "$1")
category=${mime%%/*}
kind=${mime##*/}
ext=${1##*.}

if [ "$kind" = json ]; then
    jq -Cr . "$1"
elif [ -d "$1" ]; then
	exa -1F --group-directories-first --icons --git "$1"
elif [ "$category" = image ]; then
	exiftool "$1" | bat --color=always -plyaml
elif [ "$category" = text ]; then
	bat --color=always "$1"
else
	exit 1
fi