format = """
$directory\
$docker_context\
$ruby\
$nodejs\
$git_branch\
$git_commit\
$git_state\
$git_status\
$sudo\
$cmd_duration\
$battery\
$line_break\
$character
"""

add_newline = true

[character]
success_symbol = '[➜](bold green) '
error_symbol = '[✗](bold red) '

[directory]
truncation_length = 0
truncate_to_repo = false
read_only =	' 🔒'
repo_root_style = 'underline white'
home_symbol = '~'

[directory.substitutions]
# '~/Proyects' = '💩'

[sudo]
disabled = false
symbol = '💪 '
format = '$symbol($style)'

[ruby]
format = '[$symbol($version)]($style)'

[docker_context]
format = '$symbol'

[git_branch]
format = ' [$symbol$branch(:$remote_branch)]($style) '

[git_status]
# format = '([$all_status$ahead_behind]($style) )'

[battery]
discharging_symbol = '💀 '

[[battery.display]]
threshold = 40
style = 'bold red'

# Disables the custom module
[custom]
disabled = false

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

